INSERT INTO courses(school_id, course_name, professor_name, course_title) VALUES
    (1, 'FLL 23500', 'Daniel Hsieh', 'East Asian Literature-Honors'),
    (1, 'FLL 49000', 'Benjamin R. Lawton', 'Terrorism & The Movies'),
    (1, 'FLL 49900', 'Alejandro Cuza-Blanco', 'Research Spanish Bilingualism'),
    (1, 'FLL 59600', 'Atsushi Fukada', 'Intro To Corpus Linguistics'),
    (1, 'FLL 59600', 'Robert M. Hammond', 'Applied Experimental Phonetics'),
    (1, 'FLL 59600', 'Robert Channon', 'Phonetics Of Foreign Languages'),
    (1, 'FLL 59600', 'Robert Channon', 'Morph & Morphophon'),
    (1, 'FLL 59600', 'Jessica L. Sturm', 'Topics In Pedagogy'),
    (1, 'FLL 59300', 'Howard Mancing', 'The Continental Novel'),
    (1, 'FLL 59300', 'Paula E. Leverage', 'Writing And Resistance'),
    (1, 'FLL 59600', 'John D. Sundquist', 'Topics In SLA Studies'),
    (1, 'FLL 59600', 'Robert Channon', 'Indo-European Language Family'),
    (1, 'FLL 59300', 'Paula E. Leverage', 'Women Writing War'),
    (1, 'FLL 59600', 'Kazumi Hatasa', 'Technological LitrcyFL Teacher'),
    (1, 'FLL 59600', 'Atsushi Fukada', 'Intro To Pragmatics'),
    (1, 'FLL 59600', 'Kazumi Hatasa', 'Tech App Foreign Lang Instrctn'),
    (1, 'FLL 63900', 'Shaun F. Hughes', 'Gender&Nation West Africa Fict'),
    (1, 'FLL 65000', 'Germina N. Veldwachter', 'Postcolonial Lit'),
    (1, 'FLL 65000', 'Elena Coda', 'Modern&Postmod Lndscapes'),
    (1, 'FLL 63900', 'Jeffrey Turco', 'Nibelung Lgnd & Imgnry Mid Age'),
    (1, 'FLL 67900', 'Robert Channon', 'Indo-European Language Family'),
    (1, 'FLL 67900', 'Alejandro Cuza-Blanco', 'Bilingualism & Lang Acq'),
    (1, 'FLL 67900', 'Mariko M. Wei', 'Ind Diff In Sec Lang Acq'),
    (1, 'FLL 67900', 'Mariko M. Wei', 'Clsrm Second Lang Acquisition'),
    (1, 'FLL 67900', 'Robert M. Hammond', 'Structure Of Basque'),
    (1, 'FLL 67900', 'Colleen A. Neary-Sundquist', 'Materials Dev In Lang Teaching'),
    (1, 'FLL 67900', 'Mariko M. Wei', 'Vocabulary And Reading In SLA'),
    (1, 'FLL 67900', 'John D. Sundquist', 'Research Dsgn Stdy L2 Reading');